SYSTEM:
  NUM_GPUS: 4
  FP16: False
TRAIN:
  TASK: 'ImageClassifyTask'
  CUDNN_BENCHMARK: True
  TRAIN_DATA: '/data/cifar10'
  VALID_DATA: '/data/cifar10'
  BATCH_SIZE: 512
OPTIMIZER:
  NAME: SGD
  LR: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
SCHEDULER:
  VERBOSE: True
  PATIENCE: 10
  THRESHOLD: 1e-4
