SYSTEM:
  NUM_GPUS: 1
  FP16: False
  NUM_WORKERS: 8
TRAIN:
  TASK: 'Cifar10Task'
  CUDNN_BENCHMARK: True
  TRAIN_DATA: '/data1/cifar10'
  VALID_DATA: '/data1/cifar10'
  BATCH_SIZE: 128
  PRINT_FREQ: 100
  EPOCHS: 300
  CHECKPT_PATH: '/data1/cifar10/checkpoint'
OPTIMIZER:
  TYPE: SGD
  BASE_LR: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 5e-4
SCHEDULER:
  TYPE: 'CosineAnnealingLR'
  MIN_LR: 0.0
  WARM_UP: True
  WARM_UP_EPOCHS: 4
