SYSTEM:
  NUM_GPUS: 1
  FP16: False
TRAIN:
  TASK: 'ImageClassifyTask'
  CUDNN_BENCHMARK: True
  TRAIN_DATA: '/data1/imagenet/train'
  VALID_DATA: '/data1/imagenet/val'
  BATCH_SIZE: 32
OPTIMIZER:
  NAME: SGD
  LR: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
SCHEDULER:
  VERBOSE: True
  PATIENCE: 10
  THRESHOLD: 1e-4
