SYSTEM:
  NUM_GPUS: 1
  FP16: True
TRAIN:
  CUDNN_BENCHMARK: True
  TRAIN_DATA: '/data1/imagenet/val'
  VALID_DATA: '/data1/imagenet/val'
  BATCH_SIZE: 128
OPTIMIZER:
  NAME: SGD
  LR: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
SCHEDULER:
  VERBOSE: True
  PATIENCE: 5
  THRESHOLD: 1e-3
