SYSTEM:
  NUM_GPUS: 4
  FP16: True
  NUM_WORKERS: 40
TRAIN:
  TASK: 'ImageClassifyTask'
  CUDNN_BENCHMARK: True
  TRAIN_DATA: '/data1/cifar10'
  VALID_DATA: '/data1/cifar10'
  BATCH_SIZE: 1024
  PRINT_FREQ: 100
  EPOCHS: 100
  CHECKPT_PATH: 'checkpoint'
OPTIMIZER:
  TYPE: SGD
  BASE_LR: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 5e-4
SCHEDULER:
  TYPE: 'CosineAnnealingLR'
  MIN_LR: 0.0
  WARM_UP: True
  WARM_UP_EPOCHS: 5
